main: net.tfminecraft.PointShop.PointShop
api-version: 1.20
name: PointShop
version: 1.0
author: Drefvelin

depend: [TLibs]

commands:
  pointshop:
      useage: /<command>
      description: PointShop Command